### PR TITLE
Add policy-controller policy

### PR DESCRIPTION
**Pull request by BobyMCbobs**
adds a policy for policy-controller itself

### CODE REVIEW

**Comment by hectorj2f** [comment]
Thanks @BobyMCbobs! Could you add a test case for this policy here https://github.com/chainguard-dev/policy-catalog/blob/main/policies/sigstore-landscape/policies_test.go#L15 ?

**Comment by BobyMCbobs** [comment]
@hectorj2f, I've added the test case and rebased. Thank you!

**Comment by BobyMCbobs** [comment]
> Lgtm We still need to solve the problems with the commit CI check.

@hectorj2f, let me know what is needed. I've signed my commits with my GPG key which is linked to my GitHub account.

**Comment by hectorj2f** [comment]
@BobyMCbobs Could you sign the commit following this instructions https://docs.sigstore.dev/gitsign/overview/ ? I'll add this step to CONTRIBUTING.md.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Could you sign the commit following this instructions https://docs.sigstore.dev/gitsign/overview/ ? I'll add this step to CONTRIBUTING.md.

@hectorj2f, thanks for the hand there. Just amended the commit and it is now signed with Gitsign.
Also fixed the failing test here https://github.com/chainguard-dev/policy-catalog/actions/runs/4984632436/jobs/9024872537?pr=6

**Comment by hectorj2f** [comment]
@BobyMCbobs Thanks for the contribution 🎉 !

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Thanks for the contribution 🎉 !

Thank you @hectorj2f! I hope to contribute more in the future!

**Pull request merged**
